#!/usr/bin/env python3
"""
opencode_engine.py — OpenCode engine generator (OpenCode v2).

Reads .kilo/ (source of truth) and emits .opencode/ (agents, commands,
instructions) plus root opencode.json targeting the OpenCode **v2** schema.

History:
  .opencode/ was removed in v4.0.0, reintroduced in v4.2.0 for OpenCode v1.18.
  v1.18 shipped as npm `opencode-ai`; the v2 line ships as `@opencode/cli`
  (verified 2026-09-27: `opencode-ai` latest = 1.18.32, `@opencode/cli`
  latest = 2.0.18, plugin SDK `@opencode-ai/plugin` -> `@opencode/plugin`).
  The v2 config surface is not backward compatible, so this engine now emits
  v2 shapes only. See opencode.ai/v2/docs/{config,permissions,agents,providers,
  instructions}.

Transform rules (source -> OpenCode v2):
  - agents:   .kilo/agents/*.md   -> .opencode/agents/*.md
              Kilo's `permission:` object is rewritten to v2's ordered
              `permissions:` array. `bash` -> `shell`, `task` -> `subagent`,
              and `codesearch`/`mcp` are dropped (no v2 action). Within a
              permission map the exact `*` rule is emitted first so the more
              specific rules follow it: v2 resolves with last-match-wins,
              while Kilo resolves the most specific match.
  - commands: .kilo/command/*.md  -> .opencode/commands/*.md (verbatim)
  - skills:   NOT mirrored. OpenCode v2 loads `.opencode/skills/` AND the
              Claude-compatible `.claude/skills/` and `.agents/skills/`
              (docs: Skills > Discovery). Mirroring .kilo/skill into a second
              location would register every skill twice, so OpenCode relies on
              `.claude/skills/` (generated by claude_engine) and this engine
              prunes any legacy `.opencode/skills/` mirror.
              Skills whose frontmatter sets `disable-model-invocation: true`
              become `permission.skill[name] = "ask"` in opencode.json, since
              OpenCode ignores that Claude-only field (see collect_disabled_skills).
  - instructions: OpenCode v2 accepts an `instructions` config array but does
              not resolve it, and loads only `AGENTS.md` (docs: Instructions >
              Configuration). File-type rules should not bloat the
              always-loaded AGENTS.md, so `.kilo/instruction/*.md` become
              on-demand skills under `.opencode/skills/<id>/SKILL.md`, which v2
              advertises by description and loads only when relevant. Any
              legacy `.opencode/instruction/` mirror is pruned.
  - config:   split across two files because the host IDE's OpenCode v1
              (`kilo.exe`) strictly validates the root config and hard-rejects
              v2-only keys. Root `opencode.json` keeps only v1-safe keys
              (`$schema`, `model`, `small_model`, `default_agent`, `agents`,
              `permission`); `.opencode/opencode.json` carries the v2-only
              self-contained `commandcode` provider (replacing the retired v1
              plugin `commandcode-go-opencode-provider`). OpenCode v2 merges the
              local file with higher precedence; Kilo's validator ignores it.
              The permission gate uses the legacy `permission` object for the
              same reason (v2 maps and enforces it). Only the `commandcode/<id>`
              models the harness references are declared (_PROVIDER_MODELS).
"""

from __future__ import annotations

import contextlib
import json
import shutil
from pathlib import Path
from typing import Any

TOOLS_DIR = Path(__file__).resolve().parent
ROOT_DIR = TOOLS_DIR.parent

# Kilo permission keys with no OpenCode v2 equivalent tool.
_DROP_PERMISSION_KEYS = {"codesearch", "mcp"}

# Kilo permission keys renamed in OpenCode v2 (docs: Permissions > Configure).
_PERMISSION_ACTION_RENAME = {"bash": "shell", "task": "subagent"}

# OpenCode-side action for skills whose Kilo/Claude frontmatter sets
# `disable-model-invocation: true`. OpenCode ignores that field and has no
# user-only skill invocation, so "ask" is the closest faithful mapping: the
# model may request the skill, but the user approves before it loads.
_DISABLED_SKILL_PERMISSION = "ask"

# Models the harness references, declared explicitly because the v2 provider is
# self-contained and no longer inherits the retired v1 plugin's catalog. The key
# is the harness-facing `commandcode/<key>` id; `modelID` is the upstream
# Command Code catalog id (verified via GET {COMMANDCODE_BASE_URL}/models,
# 2026-09-27). Only referenced models are declared -- add one here when a new
# `commandcode/<id>` reference is introduced.
_PROVIDER_ID = "commandcode"
_DEFAULT_MODEL = "commandcode/deepseek-v4-pro"
_SMALL_MODEL = "commandcode/deepseek-v4.1-flash"
# FreeModel's `/v1/models` is stale: it still lists `gpt-6-luna` (now HTTP 404)
# and omits `gpt-6.1-sol`. Verified 2026-10-03 by posting a chat completion to
# each id: `gpt-6-sol` and `gpt-6-astra` answer as themselves, `gpt-6.1-sol`
# answers (routed to gpt-6-sol), every other name falls back to gpt-6-sol too.
# Limits mirror models.dev's `openai` catalog for the same ids.
_FREEMODEL_MODELS: dict[str, dict[str, Any]] = {
    "gpt-6-sol": {
        "modelID": "gpt-6-sol",
        "name": "GPT-6 Sol",
        "limit": {"context": 1050000, "output": 128000},
    },
    "gpt-6-astra": {
        "modelID": "gpt-6-astra",
        "name": "GPT-6 Astra",
        "limit": {"context": 1050000, "output": 128000},
    },
    "gpt-6.1-sol": {
        "modelID": "gpt-6.1-sol",
        "name": "GPT-6.1 Sol",
        "limit": {"context": 1050000, "output": 128000},
    },
}
_PROVIDER_MODELS: dict[str, dict[str, Any]] = {
    "deepseek-v4-pro": {
        "modelID": "deepseek/deepseek-v4-pro",
        "name": "DeepSeek V4 Pro",
        "limit": {"context": 1000000, "output": 384000},
    },
    "deepseek-v4-flash": {
        "modelID": "deepseek/deepseek-v4-flash",
        "name": "DeepSeek V4 Flash",
        "limit": {"context": 1000000, "output": 384000},
    },
    "deepseek-v4.1-flash": {
        "modelID": "deepseek/deepseek-v4.1-flash",
        "name": "DeepSeek V4.1 Flash",
        "limit": {"context": 1000000, "output": 384000},
    },
    "gpt-5.4-mini": {
        "modelID": "gpt-5.4-mini",
        "name": "GPT-5.4 Mini",
        "limit": {"context": 400000, "output": 128000},
    },
    "glm-5": {
        "modelID": "zai-org/GLM-5",
        "name": "GLM-5",
        "limit": {"context": 200000, "output": 131072},
    },
    "glm-5.1": {
        "modelID": "zai-org/GLM-5.1",
        "name": "GLM-5.1",
        "limit": {"context": 200000, "output": 131072},
    },
    "qwen3.7-max": {
        "modelID": "Qwen/Qwen3.7-Max",
        "name": "Qwen 3.7 Max",
        "limit": {"context": 1000000, "output": 131072},
    },
    "qwen3.6-plus": {
        "modelID": "Qwen/Qwen3.6-Plus",
        "name": "Qwen 3.6 Plus",
        "limit": {"context": 1000000, "output": 131072},
    },
    # Added 2026-10-06 from plan.md (Step 5 Preview). `modelID` and `context`
    # verified against GET {COMMANDCODE_BASE_URL}/models (84-model catalog,
    # 2026-10-06); `output` caps are family estimates, not from the catalog.
    # "Muse Spark 1.3 Max" has no catalog id -- only `meta/muse-spark-1.3`;
    # "Space Bunny Alpha" and "Jev" are absent (Jev is an agent, not a model).
    "deepseek-v4.1-flash-fast": {
        "modelID": "deepseek/deepseek-v4.1-flash-fast",
        "name": "DeepSeek V4.1 Flash Fast",
        "limit": {"context": 1000000, "output": 384000},
    },
    "claude-sonnet-5.5": {
        "modelID": "claude-sonnet-5-5",
        "name": "Claude Sonnet 5.5",
        "limit": {"context": 1000000, "output": 131072},
    },
    "claude-opus-5.5": {
        "modelID": "claude-opus-5-5",
        "name": "Claude Opus 5.5",
        "limit": {"context": 1000000, "output": 131072},
    },
    "glm-5.3-flashx": {
        "modelID": "z-ai/glm-5.3-flashx",
        "name": "GLM-5.3 FlashX",
        "limit": {"context": 1000000, "output": 131072},
    },
    "muse-spark-1.3": {
        "modelID": "meta/muse-spark-1.3",
        "name": "Muse Spark 1.3",
        "limit": {"context": 1048576, "output": 131072},
    },
    "gpt-6.1-sol": {
        "modelID": "gpt-6.1-sol",
        "name": "GPT-6.1 Sol",
        "limit": {"context": 1050000, "output": 128000},
    },
    "gpt-6-sol": {
        "modelID": "gpt-6-sol",
        "name": "GPT-6 Sol",
        "limit": {"context": 1050000, "output": 128000},
    },
    "gpt-6-luna": {
        "modelID": "gpt-6-luna",
        "name": "GPT-6 Luna",
        "limit": {"context": 1050000, "output": 128000},
    },
    "ling-3.1-flash": {
        "modelID": "inclusionai/ling-3.1-flash:free",
        "name": "Ling 3.1 Flash",
        "limit": {"context": 262144, "output": 131072},
    },
    "mimo-v2.6-pro": {
        "modelID": "xiaomi/mimo-v2.6-pro",
        "name": "MiMo V2.6 Pro",
        "limit": {"context": 1048576, "output": 131072},
    },
    "mimo-v2.6-flash": {
        "modelID": "xiaomi/mimo-v2.6-flash",
        "name": "MiMo V2.6 Flash",
        "limit": {"context": 1048576, "output": 131072},
    },
    "grok-4.7": {
        "modelID": "xai/grok-4.7",
        "name": "Grok 4.7",
        "limit": {"context": 500000, "output": 131072},
    },
    "qwen3.8-omni-flash": {
        "modelID": "Qwen/Qwen3.8-Omni-Flash",
        "name": "Qwen 3.8 Omni Flash",
        "limit": {"context": 1000000, "output": 131072},
    },
    "step-5-preview": {
        "modelID": "stepfun/Step-5-Preview",
        "name": "Step 5 Preview",
        "limit": {"context": 1000000, "output": 131072},
    },
}

# Official DeepSeek API provider (plan.md A1). OpenAI-compatible endpoint fed by
# DEEPSEEK_API_KEY + DEEPSEEK_BASE_URL from .env (see .env.template).
# Verified 2026-10-06 against GET {DEEPSEEK_BASE_URL}/models: the official API
# serves only these two ids. There is NO `deepseek-v4.1-flash` on the direct API
# -- that id lives on CommandCode and OpenRouter instead. The /models response
# omits context_length, so the context below is the harness 1M convention, not a
# measured value.
_DEEPSEEK_MODELS: dict[str, dict[str, Any]] = {
    "deepseek-v4-pro": {
        "modelID": "deepseek-v4-pro",
        "name": "DeepSeek V4 Pro (official)",
        "limit": {"context": 1000000, "output": 384000},
    },
    "deepseek-flash": {
        "modelID": "deepseek-flash",
        "name": "DeepSeek Flash (official)",
        "limit": {"context": 1000000, "output": 384000},
    },
}

# OpenRouter provider -- an extra route to the DeepSeek models (plan.md A1, D2).
# OpenRouter's endpoint is a fixed public constant, so it is written here rather
# than read from .env; only the key is secret. DeepSeek ids verified against
# GET https://openrouter.ai/api/v1/models (465 models, 2026-10-06); OpenRouter
# reports a 1,048,576-token context for the V4 family. The `:batch` and
# `~`-prefixed alias ids are intentionally excluded.
_OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
_OPENROUTER_MODELS: dict[str, dict[str, Any]] = {
    "deepseek-v4.1-flash": {
        "modelID": "deepseek/deepseek-v4.1-flash",
        "name": "DeepSeek V4.1 Flash (OpenRouter)",
        "limit": {"context": 1048576, "output": 384000},
    },
    "deepseek-v4-pro": {
        "modelID": "deepseek/deepseek-v4-pro",
        "name": "DeepSeek V4 Pro (OpenRouter)",
        "limit": {"context": 1048576, "output": 384000},
    },
    "deepseek-v4-flash": {
        "modelID": "deepseek/deepseek-v4-flash",
        "name": "DeepSeek V4 Flash (OpenRouter)",
        "limit": {"context": 1048576, "output": 384000},
    },
    "deepseek-v4-flash-vision-exp": {
        "modelID": "deepseek/deepseek-v4-flash-vision-exp",
        "name": "DeepSeek V4 Flash Vision Exp (OpenRouter)",
        "limit": {"context": 1048576, "output": 384000},
    },
}

# Ordered shell allow/deny rules for the legacy `permission.bash` object.
#
# Why the legacy shape: the host IDE (Kilo Code 7.8.1) bundles OpenCode v1 in
# `kilo.exe`, whose `config check` hard-rejects a top-level `permissions` array
# ("V2 permissions are not supported by OpenCode V1"). OpenCode v2 maps and
# enforces this legacy `permission` object 1:1 (verified 2026-09-28:
# `opencode debug agents` shows these exact rules on every agent), so the
# shared shape is what both readers accept. Broad rules precede specific ones
# because the last matching rule wins.
_BASE_BASH_RULES: list[tuple[str, str]] = [
    ("*", "ask"),
    ("python .github/scripts/security_scan.py *", "allow"),
    ("python .github/scripts/checklist.py *", "allow"),
    ("python tools/antigravity_delegate.py *", "ask"),
    ("git status*", "allow"),
    ("git diff*", "allow"),
    ("git log*", "allow"),
    ("git add*", "allow"),
    ("git commit*", "allow"),
    ("git push*", "ask"),
    ("git reset --hard*", "deny"),
    ("git push --force*", "deny"),
    ("rm -rf *", "deny"),
    ("del /s /q *", "deny"),
    ("DROP TABLE*", "deny"),
    ("DROP DATABASE*", "deny"),
]


def _write_if_changed(path: Path, content: str) -> None:
    """Write `content` as LF text, but only when it differs from what is there.

    An unconditional write bumps mtime, and `git status` then reports every
    generated artifact as modified while `git diff` shows nothing at all -- it
    compares stat first and only reads content on `git diff`. Mirrors the guard
    in claude_engine._write_lf.
    """
    if path.exists():
        with contextlib.suppress(OSError, UnicodeDecodeError):
            if path.read_text(encoding="utf-8") == content:
                return
    path.write_text(content, encoding="utf-8", newline="")


def _copy_if_changed(src: Path, dst: Path) -> None:
    """Copy `src` over `dst` only when the bytes actually differ."""
    data = src.read_bytes()
    if dst.exists():
        with contextlib.suppress(OSError):
            if dst.read_bytes() == data:
                return
    dst.write_bytes(data)


def _frontmatter_block(text: str) -> str | None:
    """Return the text between the opening and closing `---` fences, or None."""
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    return text[3:end]


def collect_disabled_skills(kilo_root: Path) -> dict[str, str]:
    """Map skill name -> permission action for skills marked
    `disable-model-invocation: true` in .kilo/skill/<name>/SKILL.md.
    """
    out: dict[str, str] = {}
    skill_root = kilo_root / "skill"
    if not skill_root.is_dir():
        return out
    for skill_dir in sorted(p for p in skill_root.iterdir() if p.is_dir()):
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.is_file():
            continue
        fm = _frontmatter_block(skill_md.read_text(encoding="utf-8"))
        if fm is None:
            continue
        for line in fm.splitlines():
            key, _, value = line.partition(":")
            if key.strip() == "disable-model-invocation" and value.strip().lower() == "true":
                out[skill_dir.name] = _DISABLED_SKILL_PERMISSION
                break
    return out


def _parse_permission_block(frontmatter: str) -> tuple[list[str], list[tuple[str, list[tuple[str, str]]]]]:
    """Split an agent frontmatter into (kept lines, permission entries).

    `kept lines` are every frontmatter line outside the `permission:` block,
    preserved verbatim and in order. `permission entries` are ordered
    (action, [(resource, effect), ...]) pairs; a scalar permission such as
    `edit: allow` becomes a single `("*", "allow")` rule.
    """
    kept: list[str] = []
    entries: list[tuple[str, list[tuple[str, str]]]] = []
    lines = frontmatter.split("\n")
    i = 0
    while i < len(lines):
        raw = lines[i]
        if raw.strip() != "permission:":
            kept.append(raw)
            i += 1
            continue

        # Collect the permission block's child lines until the next dedent.
        children: list[tuple[int, str, str | None]] = []
        i += 1
        while i < len(lines):
            nxt = lines[i]
            if not nxt.strip():
                i += 1
                continue
            indent = len(nxt) - len(nxt.lstrip(" "))
            if indent == 0:
                break
            key, sep, value = nxt.strip().partition(":")
            key = key.strip().strip('"').strip("'")
            children.append((indent, key, value.strip() if sep else None))
            i += 1

        idx = 0
        while idx < len(children):
            indent, key, value = children[idx]
            if value:
                entries.append((key, [("*", value)]))
                idx += 1
                continue
            rules: list[tuple[str, str]] = []
            idx += 1
            while idx < len(children) and children[idx][0] > indent:
                _, resource, effect = children[idx]
                rules.append((resource, effect or ""))
                idx += 1
            entries.append((key, rules))

    while kept and not kept[-1].strip():
        kept.pop()
    return kept, entries


def _render_permissions(entries: list[tuple[str, list[tuple[str, str]]]]) -> list[str]:
    """Render permission entries as a v2 `permissions:` YAML block sequence.

    The exact `*` rule is emitted before the rest so specific rules win under
    v2's last-match-wins resolution.
    """
    rules: list[tuple[str, str, str]] = []
    for action, children in entries:
        if action in _DROP_PERMISSION_KEYS:
            continue
        mapped = _PERMISSION_ACTION_RENAME.get(action, action)
        ordered = [c for c in children if c[0] == "*"] + [c for c in children if c[0] != "*"]
        for resource, effect in ordered:
            if not effect:
                continue
            rules.append((mapped, resource, effect))
    if not rules:
        return []
    out = ["permissions:"]
    for action, resource, effect in rules:
        out.append(f"  - action: {action}")
        out.append(f'    resource: "{resource}"')
        out.append(f"    effect: {effect}")
    return out


def _convert_agent_frontmatter(frontmatter: str) -> str:
    kept, entries = _parse_permission_block(frontmatter)
    rendered = kept + _render_permissions(entries)
    return "\n".join(rendered).rstrip("\n")


def generate_agents(kilo_root: Path, opencode_root: Path) -> int:
    src_dir = kilo_root / "agents"
    dst_dir = opencode_root / "agents"
    if not src_dir.is_dir():
        print(f"[ERROR] Source agent directory not found: {src_dir}")
        return 1
    dst_dir.mkdir(parents=True, exist_ok=True)
    copied = 0
    for agent_file in sorted(src_dir.glob("*.md")):
        content = agent_file.read_text(encoding="utf-8")
        split = content.split("---", 2)
        if len(split) < 3:
            print(f"  [SKIP] agents/{agent_file.name} (no frontmatter)")
            continue
        fm = _convert_agent_frontmatter(split[1].strip("\n"))
        body = split[2].lstrip("\n")
        new_content = f"---\n{fm}\n---\n{body}"
        _write_if_changed(dst_dir / agent_file.name, new_content)
        copied += 1
        print(f"  [GEN] agents/{agent_file.name}")
    print(f"OpenCode agents generated: {copied}")
    return 0


def generate_commands(kilo_root: Path, opencode_root: Path) -> int:
    src_dir = kilo_root / "command"
    dst_dir = opencode_root / "commands"
    if not src_dir.is_dir():
        print(f"[ERROR] Source command directory not found: {src_dir}")
        return 1
    dst_dir.mkdir(parents=True, exist_ok=True)
    copied = 0
    for cmd_file in sorted(src_dir.glob("*.md")):
        content = cmd_file.read_text(encoding="utf-8")
        _write_if_changed(dst_dir / cmd_file.name, content)
        copied += 1
        print(f"  [GEN] commands/{cmd_file.name}")
    print(f"OpenCode commands generated: {copied}")
    return 0


def prune_duplicate_skills(kilo_root: Path, opencode_root: Path) -> int:
    """Remove any `.opencode/skills/<id>` that mirrors a `.kilo/skill/<id>`.

    OpenCode loads `.opencode/skills/` plus the Claude-compatible
    `.claude/skills/`, so the same skill id in both registers twice. The
    `.opencode/skills/` directory itself is now used for instruction-derived
    skills (see generate_instruction_skills), so only mirror ids are pruned --
    never the whole directory.
    """
    dst = opencode_root / "skills"
    src = kilo_root / "skill"
    if not dst.is_dir() or not src.is_dir():
        print("  [OK] no skill mirror to prune")
        return 0
    kilo_ids = {p.name for p in src.iterdir() if p.is_dir()}
    removed = 0
    for d in sorted(p for p in dst.iterdir() if p.is_dir()):
        if d.name in kilo_ids:
            shutil.rmtree(d)
            print(f"  [PRUNE] skills/{d.name}/ (mirrors .kilo/skill — already in .claude/skills)")
            removed += 1
    if not removed:
        print("  [OK] no skill mirror to prune")
    return removed


def prune_instructions(opencode_root: Path) -> int:
    """Remove `.opencode/instruction/` if a legacy v1 mirror is present.

    v1 loaded instruction files through the `instructions` config glob. v2 does
    not resolve that field and reads only `AGENTS.md`, so the mirror is dead
    weight; generate_instruction_skills() emits them as on-demand skills.
    """
    dst = opencode_root / "instruction"
    if dst.exists():
        shutil.rmtree(dst)
        print("  [PRUNE] instruction/ (v2 loads AGENTS.md — removed)")
        return 1
    print("  [OK] instruction/ absent (v2 reads AGENTS.md)")
    return 0


def _yaml_quote(value: str) -> str:
    """Return `value` as a YAML double-quoted scalar."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _instruction_skill_doc(path: Path) -> tuple[str, str]:
    """Derive (name, description) for an instruction-derived skill.

    The name comes from the first `# Heading`; the description from the
    leading `> ...` usage note (the "Auto-loaded when ..." line), otherwise the
    first non-heading line.
    """
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    name = path.stem
    for line in lines:
        if line.startswith("# "):
            name = line[2:].strip()
            break
    description = ""
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("> "):
            description = stripped[2:].strip()
            break
    if not description:
        for line in lines:
            stripped = line.strip()
            if stripped and not stripped.startswith("#"):
                description = stripped
                break
    if not description:
        description = f"Project instruction rules from {path.name}"
    return name, description


def generate_instruction_skills(kilo_root: Path, opencode_root: Path) -> int:
    """Emit .kilo/instruction/*.md as on-demand OpenCode v2 skills.

    v2 loads only AGENTS.md for always-on guidance; file-type rules are better
    modelled as skills, which v2 advertises by description and loads only when
    relevant (docs: Skills). Each instruction file becomes
    `.opencode/skills/<stem>/SKILL.md`. The stems were checked against the
    `.claude/skills` mirror, so ids never collide there. Skill dirs whose
    source instruction was removed are pruned.
    """
    src_dir = kilo_root / "instruction"
    dst_dir = opencode_root / "skills"
    if not src_dir.is_dir():
        print(f"[ERROR] Source instruction directory not found: {src_dir}")
        return 1
    dst_dir.mkdir(parents=True, exist_ok=True)
    generated = 0
    expected: set[str] = set()
    for src in sorted(src_dir.glob("*.md")):
        expected.add(src.stem)
        name, description = _instruction_skill_doc(src)
        body = src.read_text(encoding="utf-8").rstrip()
        content = (
            "---\n"
            f"name: {_yaml_quote(name)}\n"
            f"description: {_yaml_quote(description)}\n"
            "---\n\n"
            f"{body}\n"
        )
        skill_dir = dst_dir / src.stem
        skill_dir.mkdir(parents=True, exist_ok=True)
        _write_if_changed(skill_dir / "SKILL.md", content)
        generated += 1
        print(f"  [GEN] skills/{src.stem}/SKILL.md")
    for existing in sorted(p for p in dst_dir.iterdir() if p.is_dir()):
        if existing.name not in expected:
            shutil.rmtree(existing)
            print(f"  [PRUNE] skills/{existing.name}/ (no source instruction)")
    print(f"OpenCode instruction skills generated: {generated}")
    return 0


def generate_opencode_json(
    opencode_root: Path,
    root_dir: Path,
    disabled_skills: dict[str, str] | None = None,
) -> int:
    """Write root opencode.json in the OpenCode v2 schema.

    The config is split across two files because the host IDE's OpenCode v1
    (`kilo.exe`) strictly validates the root `opencode.json` and hard-rejects
    v2-only keys:
      - root `opencode.json` -> v1-safe keys only (`$schema`, `model`,
        `small_model`, `default_agent`, `agents`, `permission`), so
        `kilo config check` stays clean.
      - `.opencode/opencode.json` -> the v2-only self-contained
        `providers.commandcode` and `providers.freemodel` blocks (replacing
        the retired v1 plugin `commandcode-go-opencode-provider`). OpenCode v2
        merges this file with higher precedence; Kilo's validator ignores it.

    The gate uses the legacy `permission` object (not v2's `permissions`
    array) for the same reason: Kilo's bundled v1 rejects `permissions`, while
    OpenCode v2 maps and enforces the legacy shape (see _BASE_BASH_RULES).

    `disabled_skills` maps skill name -> action for skills whose Kilo/Claude
    frontmatter sets `disable-model-invocation: true`; it becomes
    `permission.skill[name] = "ask"`.
    """
    permission: dict[str, Any] = {
        "edit": "ask",
        "external_directory": "ask",
        "bash": dict(_BASE_BASH_RULES),
    }
    if disabled_skills:
        # "*" first, specific rules last (last matching rule wins).
        skill_rules: dict[str, str] = {"*": "allow"}
        for name in sorted(disabled_skills):
            skill_rules[name] = disabled_skills[name]
        permission["skill"] = skill_rules

    root_config: dict[str, Any] = {
        "$schema": "https://opencode.ai/config.json",
        "model": _DEFAULT_MODEL,
        "small_model": _SMALL_MODEL,
        "default_agent": "solo-code-engineer",
        "agents": {"solo-code-engineer": {"model": _DEFAULT_MODEL}},
        "permission": permission,
    }
    local_config: dict[str, Any] = {
        "$schema": "https://opencode.ai/config.json",
        "providers": {
            _PROVIDER_ID: {
                "name": "Command Code",
                "env": ["COMMANDCODE_API_KEY"],
                "package": "@opencode/ai/providers/openai-compatible",
                # v2 rejects `{env:NAME}` references in *project* config
                # (only global config may use them). `${NAME}` is the
                # server-environment placeholder and is accepted here; the
                # launcher exports COMMANDCODE_BASE_URL to that server.
                "settings": {"baseURL": "${COMMANDCODE_BASE_URL}"},
                "models": _PROVIDER_MODELS,
            },
            "freemodel": {
                "name": "FreeModel",
                # A dedicated var, not OPENAI_API_KEY: OpenCode's built-in OpenAI
                # provider also claims OPENAI_API_KEY, and a credential stored
                # for `freemodel` overrides this env var entirely (the launcher
                # clears the stored one each launch).
                "env": ["FREEMODEL_API_KEY"],
                "package": "@opencode/ai/providers/openai-compatible",
                # `OPENAI_BASE_URL` is the bare host; the `/v1` path must be
                # appended here because the OpenAI-compatible provider POSTs to
                # `<baseURL>/chat/completions` verbatim (no /v1 auto-append).
                "settings": {"baseURL": "${OPENAI_BASE_URL}/v1"},
                "models": _FREEMODEL_MODELS,
            },
            "deepseek": {
                "name": "DeepSeek (official)",
                # Direct DeepSeek API, not a proxy. Both vars come from .env via
                # opencode-env.ps1; the template ships https://api.deepseek.com/v1.
                "env": ["DEEPSEEK_API_KEY"],
                "package": "@opencode/ai/providers/openai-compatible",
                "settings": {"baseURL": "${DEEPSEEK_BASE_URL}"},
                "models": _DEEPSEEK_MODELS,
            },
            "openrouter": {
                "name": "OpenRouter",
                # Only the key is secret; the endpoint is the public constant above.
                "env": ["OPENROUTER_API_KEY"],
                "package": "@opencode/ai/providers/openai-compatible",
                "settings": {"baseURL": _OPENROUTER_BASE_URL},
                "models": _OPENROUTER_MODELS,
            },
        },
    }
    opencode_root.mkdir(parents=True, exist_ok=True)
    _write_if_changed(root_dir / "opencode.json", json.dumps(root_config, indent=2) + "\n")
    _write_if_changed(opencode_root / "opencode.json", json.dumps(local_config, indent=2) + "\n")
    note = f" ({len(disabled_skills)} skill permission rule(s))" if disabled_skills else ""
    print(f"OpenCode config generated: opencode.json + .opencode/opencode.json{note}")
    return 0


def generate_all(
    kilo_root: Path, opencode_root: Path, root_dir: Path, *, skip_names: set[str] | None = None
) -> int:
    # skip_names is retained for call-site compatibility; this engine no longer
    # mirrors skills (see prune_duplicate_skills).
    del skip_names
    opencode_root.mkdir(parents=True, exist_ok=True)
    print("--- OpenCode agents ---")
    if generate_agents(kilo_root, opencode_root) != 0:
        return 1
    print("--- OpenCode commands ---")
    generate_commands(kilo_root, opencode_root)
    print("--- OpenCode skills ---")
    prune_duplicate_skills(kilo_root, opencode_root)
    print("--- OpenCode instructions ---")
    prune_instructions(opencode_root)
    generate_instruction_skills(kilo_root, opencode_root)
    print("--- OpenCode config ---")
    generate_opencode_json(opencode_root, root_dir, collect_disabled_skills(kilo_root))
    return 0
